<?php

function continueto_preprocess(&$variables, $hook) {
	if (isset($_SESSION['continue_to'])) {
		$url = $_SESSION['continue_to'];

		unset($_SESSION['continue_to']);
		drupal_goto($url);
	}
}

function continueto_user_login(&$edit, $account) {
	if (isset($_GET['continue_to'])) {
		$url = rawurldecode($_GET['continue_to']);
		$url = url($url, array('absolute' => true));

		$_SESSION['continue_to'] = $url;
	}
}

